openapi: 3.0.0
info:
  title: Customers API
  version: 1.0.0
paths:
  /customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Create a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerInput'
      responses:
        '201':
          description: Customer created
  /customers/{id}:
    get:
      summary: Get a customer by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the customer to retrieve
      responses:
        '200':
          description: A single customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
    put:
      summary: Update a customer by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the customer to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerInput'
      responses:
        '200':
          description: Customer updated
        '404':
          description: Customer not found
    delete:
      summary: Delete a customer by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the customer to delete
      responses:
        '204':
          description: Customer deleted
        '404':
          description: Customer not found
components:
  schemas:
    Customer:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        specialty:
          type: string
        address:
          type: string
        contactInformation:
          type: string
        tier:
          type: string
        prescribingHistory:
          type: string
        preferences:
          type: string
      required:
        - customerId
        - name
        - type
        - address
        - contactInformation
        - tier
    CustomerInput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        specialty:
          type: string
        address:
          type: string
        contactInformation:
          type: string
        tier:
          type: string
        prescribingHistory:
          type: string
        preferences:
          type: string
      required:
        - name
        - type
        - address
        - contactInformation
        - tier
