openapi: 3.0.0
info:
  title: Products API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Product created
  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the product to retrieve
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    put:
      summary: Update a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the product to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Product updated
        '404':
          description: Product not found
    delete:
      summary: Delete a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the product to delete
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: string
          format: uuid
        name:
          type: string
        category:
          type: string
        therapeuticArea:
          type: string
        launchDate:
          type: string
          format: date
        status:
          type: string
        pricing:
          type: number
          format: float
        manufacturer:
          type: string
        regulatoryInformation:
          type: string
        indication:
          type: string
      required:
        - productId
        - name
        - category
        - therapeuticArea
        - launchDate
        - status
        - pricing
        - manufacturer
    ProductInput:
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        therapeuticArea:
          type: string
        launchDate:
          type: string
          format: date
        status:
          type: string
        pricing:
          type: number
          format: float
        manufacturer:
          type: string
        regulatoryInformation:
          type: string
        indication:
          type: string
      required:
        - name
        - category
        - therapeuticArea
        - launchDate
        - status
        - pricing
        - manufacturer
